# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Come with me now on a journey through code and data... 
subtitle:
description: It's a Data Science blog 
keywords: data science, blog, katie clark, python
author: Katie Clark 
language: English
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://hello-klol.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: custom-theme
theme_config:
  favicon: 
    small: /images/favicon-16x16.png
    medium: /images/favicon-32x32.png
    apple_touch_icon: /images/apple-touch-icon.png
  # Menu
  menu:
    Home: / || home
    About: /about/ || child
    Blog: /archives/ || book
    GitHub: https://github.com/hello-klol || github-alt
    Twitter: https://twitter.com/_katie_clark_ || twitter
    StackOverflow: https://stackoverflow.com/users/1168920/katie || stack-overflow
    CV: /cv.pdf || user
  sidebar:
    display: remove
  disqus:
    enable: false 
    shortname: hello-klol
    count: true

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: '/blog'
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/hello-klol/hello-klol.github.io  
  branch: master
  message: hexo deploy    
